// <auto-generated />
using System;
using CryptoCurrencyBrowser.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoCurrencyBrowser.Persistence.Migrations
{
    [DbContext(typeof(CryptocurrencyBrowserDbContext))]
    [Migration("20191127212421_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CryptoCurrencyBrowser.Domain.Entities.Cryptocurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CirculatingSupply");

                    b.Property<decimal>("CurrentPrice");

                    b.Property<int>("ExternalId");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<decimal>("MarketCap");

                    b.Property<long>("MaxSupply");

                    b.Property<string>("Name");

                    b.Property<double>("PercentCHange7d");

                    b.Property<double>("PercentChange1h");

                    b.Property<double>("PercentChange24h");

                    b.Property<int>("Rank");

                    b.Property<string>("Symbol");

                    b.Property<long>("TotalSupply");

                    b.Property<decimal>("Volume24h");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrencies");
                });
#pragma warning restore 612, 618
        }
    }
}
